import { field, repeatGroup, type ServiceFormSchema } from '../applicationFieldSchema'

export const australiaStudentSchema: ServiceFormSchema = {
  serviceCode: 'australia-student',
  documents: [
    { id: 'passport-copy', label: 'Passport copy', labelAr: 'نسخة جواز السفر', required: true },
    {
      id: 'civil-id-copy',
      label: 'Civil ID copy',
      labelAr: 'نسخة البطاقة المدنية',
      required: true,
    },
    {
      id: 'statement-of-purpose',
      label: 'Statement of Purpose (SOP)',
      labelAr: 'بيان الغرض (SOP)',
      required: true,
    },
    {
      id: 'health-insurance-oshc',
      label: 'Health insurance (OSHC)',
      labelAr: 'التأمين الصحي (OSHC)',
      required: true,
      visibleWhen: { fieldId: 'proof-of-finance', equals: 'Sponsor' },
    },
    {
      id: 'visa-letter',
      label: 'Visa letter',
      labelAr: 'خطاب التأشيرة',
      required: true,
      visibleWhen: { fieldId: 'proof-of-finance', equals: 'Sponsor' },
    },
    {
      id: 'health-insurance-university-approved',
      label: 'Health insurance approved by the university',
      labelAr: 'تأمين صحي معتمد من الجامعة',
      required: true,
      visibleWhen: { fieldId: 'proof-of-finance', equals: 'Self-Funded' },
    },
    {
      id: 'confirmation-of-enrollment',
      label: 'Confirmation of Enrolment (CoE)',
      labelAr: 'تأكيد القيد الجامعي (CoE)',
      required: true,
    },
    {
      id: 'confirmation-of-enrollment-2',
      label: 'Confirmation of Enrolment (CoE) — additional',
      labelAr: 'تأكيد القيد الجامعي (CoE) — إضافي',
      required: true,
    },
    {
      id: 'father-passport-upload',
      label: "Father's passport",
      labelAr: 'جواز سفر الأب',
      required: true,
    },
    {
      id: 'mother-passport-upload',
      label: "Mother's passport",
      labelAr: 'جواز سفر الأم',
      required: true,
    },
    {
      id: 'brother-passport-upload',
      label: 'Passport of brother(s)',
      labelAr: 'جواز سفر الأخ/الإخوة',
      required: false,
      hint: 'Optional',
      hintAr: 'اختياري',
    },
    {
      id: 'sister-passport-upload',
      label: 'Passport of sister(s)',
      labelAr: 'جواز سفر الأخت/الأخوات',
      required: false,
      hint: 'Optional',
      hintAr: 'اختياري',
    },
    {
      id: 'guardian-bank-statement',
      label: "Guardian's bank statement",
      labelAr: 'كشف حساب ولي الأمر البنكي',
      required: true,
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
    },
    {
      id: 'guardian-passport',
      label: "Guardian's passport",
      labelAr: 'جواز سفر ولي الأمر',
      required: true,
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
    },
    {
      id: 'guardian-salary-certificate',
      label: "Guardian's salary certificate or employment letter",
      labelAr: 'شهادة راتب ولي الأمر أو خطاب تعريف بالعمل',
      required: true,
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
    },
    {
      id: 'guardian-sop',
      label: "Guardian's Statement of Purpose (SOP)",
      labelAr: 'بيان الغرض الخاص بولي الأمر (SOP)',
      required: true,
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
    },
    {
      id: 'guardian-ovhc',
      label: "Guardian's OVHC (health insurance)",
      labelAr: 'تأمين OVHC الصحي الخاص بولي الأمر',
      required: false,
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
    },
    {
      id: 'birth-certificate',
      label: 'Birth certificate in English',
      labelAr: 'شهادة الميلاد باللغة الإنجليزية',
      required: true,
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
    },
    {
      id: 'form-1229',
      label: 'Form 1229 — consent to travel',
      labelAr: 'نموذج 1229 — الموافقة على السفر',
      required: false,
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
    },
    {
      id: 'form-157n',
      label: 'Form 157N — student guardian visa application',
      labelAr: 'نموذج 157N — طلب تأشيرة ولي أمر الطالب',
      required: true,
      hint: 'Required if a parent is travelling with the student',
      hintAr: 'مطلوب إذا كان أحد الوالدين مسافرًا مع الطالب',
      visibleWhen: { fieldId: 'parent-traveling', equals: 'Yes' },
    },
    {
      id: 'caaw-form',
      label: 'CAAW form',
      labelAr: 'نموذج CAAW',
      required: true,
      hint: 'Required if the parent is not travelling with the student',
      hintAr: 'مطلوب إذا لم يكن الوالد مسافرًا مع الطالب',
      visibleWhen: { fieldId: 'parent-traveling', equals: 'No' },
    },
  ],
  fields: [
    field({
      id: 'applied-visa-before',
      type: 'radio',
      label: 'Have you previously applied for an Australian visa?',
      labelAr: 'هل تقدمت لتأشيرة أسترالية من قبل؟',
      required: true,
      defaultValue: 'No',
    }),
    field({
      id: 'email',
      type: 'email',
      label: 'Email address',
      labelAr: 'البريد الإلكتروني',
      required: true,
    }),
    field({
      id: 'phone-primary',
      type: 'tel',
      label: 'Preferred contact number',
      labelAr: 'رقم التواصل المفضل',
      required: true,
    }),
    field({
      id: 'intended-arrival-date',
      type: 'date',
      label: 'Intended arrival date in Australia',
      labelAr: 'تاريخ الوصول المتوقع إلى أستراليا',
      required: true,
    }),
    field({
      id: 'current-circumstances',
      type: 'textarea',
      label:
        'Current circumstances — including ties to family, community, employment, and economic circumstances',
      labelAr: 'ظروفك الحالية — بما يشمل ارتباطك بالعائلة والمجتمع والعمل والوضع الاقتصادي',
      required: true,
      hint: 'About 100 words',
      hintAr: 'حوالي 100 كلمة',
    }),
    field({
      id: 'course-and-provider-reason',
      type: 'textarea',
      label: 'Why do you wish to study this course in Australia with this education provider?',
      labelAr: 'لماذا ترغب بدراسة هذا البرنامج في أستراليا لدى مقدم التعليم هذا؟',
      required: true,
      hint: 'Include your understanding of the course requirements and of studying and living in Australia — about 100 words',
      hintAr: 'اذكر فهمك لمتطلبات البرنامج وللدراسة والحياة في أستراليا — حوالي 100 كلمة',
    }),
    field({
      id: 'course-benefit',
      type: 'textarea',
      label: 'How will completing this course benefit you?',
      labelAr: 'كيف ستستفيد من إتمام هذا البرنامج؟',
      required: true,
      hint: 'About 100 words',
      hintAr: 'حوالي 100 كلمة',
    }),
    field({
      id: 'other-relevant-info',
      type: 'textarea',
      label: 'Any other relevant information you would like to include',
      labelAr: 'أي معلومات أخرى ذات صلة ترغب بإضافتها',
      required: true,
    }),
    field({
      id: 'marital-status',
      type: 'select',
      label: 'Marital status',
      labelAr: 'الحالة الاجتماعية',
      required: true,
      options: ['Single', 'Married', 'Divorced', 'Widowed'],
      optionsAr: ['أعزب', 'متزوج', 'مطلق', 'أرمل'],
      defaultValue: 'Single',
    }),
    field({
      id: 'proof-of-finance',
      type: 'select',
      label: 'Proof of finance',
      labelAr: 'إثبات الملاءة المالية',
      required: true,
      options: ['Self-Funded', 'Sponsor'],
      optionsAr: ['تمويل ذاتي', 'كفيل'],
      defaultValue: 'Self-Funded',
    }),
    field({
      id: 'employment-status',
      type: 'radio',
      label: 'Are you currently employed, or do you have previous work experience?',
      labelAr: 'هل أنت موظف حاليًا أو لديك خبرة عمل سابقة؟',
      required: true,
      defaultValue: 'No',
    }),
    field({
      id: 'employment-after-course',
      type: 'textarea',
      label: 'What type of employment will you be seeking after completing your course?',
      labelAr: 'ما نوع الوظيفة التي ستبحث عنها بعد إتمام البرنامج؟',
      required: true,
    }),
    field({
      id: 'under-18',
      type: 'radio',
      label: 'Are you under 18 years of age?',
      labelAr: 'هل عمرك أقل من 18 سنة؟',
      required: true,
      defaultValue: 'No',
    }),
    // بره conditionalSection عمداً — visibleWhen على مستوى الوثائق يحتاج مرجع لحقل top-level
    // (نفس القيد اللي schema.test.ts يتحقق منه)، فما نقدر نخليه جوّة قسم "under 18" المتداخل
    field({
      id: 'parent-traveling',
      type: 'radio',
      label: 'If you are under 18: is a parent travelling to Australia with you?',
      labelAr: 'إذا كان عمرك أقل من 18 سنة: هل سيسافر أحد الوالدين معك إلى أستراليا؟',
      required: false,
      defaultValue: 'No',
    }),
    repeatGroup({
      id: 'last-3-visits-australia',
      label: 'Last 3 visits to Australia (skip if you have not been before)',
      labelAr: 'آخر 3 زيارات لأستراليا (تخطَّ هذا إذا لم تزرها من قبل)',
      count: 3,
      columns: [
        { id: 'date', type: 'date', placeholder: 'Travel date', placeholderAr: 'تاريخ السفر' },
        {
          id: 'duration-purpose',
          type: 'text',
          placeholder: 'Duration & purpose — e.g. 2 weeks, tourism',
          placeholderAr: 'المدة والغرض — مثال: أسبوعين، سياحة',
        },
      ],
    }),
    repeatGroup({
      id: 'last-5-international-flights',
      label: 'Last 5 international flights other than Australia (if applicable)',
      labelAr: 'آخر 5 رحلات دولية بخلاف أستراليا (إن وجدت)',
      count: 5,
      columns: [
        { id: 'country', type: 'text', placeholder: 'Country', placeholderAr: 'الدولة' },
        { id: 'date', type: 'date', placeholder: 'Date', placeholderAr: 'التاريخ' },
        { id: 'duration', type: 'text', placeholder: 'Duration', placeholderAr: 'المدة' },
      ],
    }),
  ],
  serviceChargeKd: 80,
}
