import { field, conditionalSection, type ServiceFormSchema } from '../applicationFieldSchema'

export const ieltsSchema: ServiceFormSchema = {
  serviceCode: 'ielts',
  documents: [
    { id: 'passport-copy', label: 'Passport copy', labelAr: 'نسخة جواز السفر', required: true },
    { id: 'upay-invoice', label: 'UPay invoice', labelAr: 'فاتورة UPay', required: true },
  ],
  fields: [
    field({
      id: 'counselor-name',
      type: 'select',
      label: 'Counselor',
      labelAr: 'المستشار',
      required: false,
      optionsSource: 'activeCounselors',
    }),
    field({
      id: 'email',
      type: 'email',
      label: 'Email',
      labelAr: 'البريد الإلكتروني',
      required: true,
    }),
    field({ id: 'address', type: 'text', label: 'Address', labelAr: 'العنوان', required: true }),
    field({
      id: 'test-type',
      type: 'select',
      label: 'Type of test',
      labelAr: 'نوع الاختبار',
      required: true,
      options: ['Select...', 'Academic', 'General Training', 'UKVI', 'I do not know'],
      optionsAr: ['اختر...', 'أكاديمي', 'عام (تدريب)', 'UKVI', 'لا أعلم'],
    }),
    field({
      id: 'test-source',
      type: 'select',
      label: 'Test source',
      labelAr: 'مصدر الاختبار',
      required: true,
      options: ['Select...', 'IDP', 'British Council', 'I do not know'],
      optionsAr: ['اختر...', 'IDP', 'British Council', 'لا أعلم'],
    }),
    conditionalSection({
      id: 'existing-account-idp',
      label: 'Existing account',
      labelAr: 'حساب حالي',
      visibleWhen: { fieldId: 'test-source', equals: 'IDP' },
      fields: [
        field({
          id: 'existing-account-username',
          type: 'text',
          label: 'Existing account username / email (if you already have one)',
          labelAr: 'اسم المستخدم / البريد الإلكتروني للحساب الحالي (إن وجد)',
          required: false,
          hint: 'No password — the counselor will get it directly from you when booking',
          hintAr: 'بدون كلمة المرور — سيحصل عليها المستشار منك مباشرة عند الحجز',
        }),
      ],
    }),
    conditionalSection({
      id: 'existing-account-british-council',
      label: 'Existing account',
      labelAr: 'حساب حالي',
      visibleWhen: { fieldId: 'test-source', equals: 'British Council' },
      fields: [
        field({
          id: 'existing-account-username',
          type: 'text',
          label: 'Existing account username / email (if you already have one)',
          labelAr: 'اسم المستخدم / البريد الإلكتروني للحساب الحالي (إن وجد)',
          required: false,
          hint: 'No password — the counselor will get it directly from you when booking',
          hintAr: 'بدون كلمة المرور — سيحصل عليها المستشار منك مباشرة عند الحجز',
        }),
      ],
    }),
    field({
      id: 'preferred-date',
      type: 'date',
      label: 'Preferred date of test',
      labelAr: 'التاريخ المفضل للاختبار',
      required: false,
    }),
    field({
      id: 'time-1st',
      type: 'select',
      label: 'Time of test — 1st choice',
      labelAr: 'وقت الاختبار — الخيار الأول',
      required: false,
      options: ['Select...', 'Morning', 'Afternoon'],
      optionsAr: ['اختر...', 'صباحًا', 'مساءً'],
    }),
    field({
      id: 'time-2nd',
      type: 'select',
      label: 'Time of test — 2nd choice',
      labelAr: 'وقت الاختبار — الخيار الثاني',
      required: false,
      options: ['Select...', 'Morning', 'Afternoon'],
      optionsAr: ['اختر...', 'صباحًا', 'مساءً'],
    }),
    field({
      id: 'registered-ielts-before',
      type: 'radio',
      label: 'Registered for IELTS before?',
      labelAr: 'هل سبق وسجلت في آيلتس من قبل؟',
      required: false,
      defaultValue: 'No',
    }),
    field({
      id: 'student-source',
      type: 'select',
      label: 'Student source',
      labelAr: 'مصدر الطالب',
      required: true,
      options: ['Select...', 'Walk in', 'WhatsApp', 'Fair / Event', 'Respond'],
      optionsAr: ['اختر...', 'حضور مباشر', 'واتساب', 'معرض / فعالية', 'Respond'],
    }),
    field({
      id: 'notes',
      type: 'textarea',
      label: 'Notes',
      labelAr: 'ملاحظات',
      required: false,
    }),
  ],
}
