import { field, conditionalSection, type ServiceFormSchema } from '../applicationFieldSchema'

export const irelandStudentSchema: ServiceFormSchema = {
  serviceCode: 'ireland-student',
  documents: [
    { id: 'passport-copy', label: 'Passport copy', labelAr: 'نسخة جواز السفر', required: true },
    {
      id: 'prior-visas',
      label: 'Previous Schengen, US, UK, Canada, Australia, or New Zealand visa',
      labelAr: 'تأشيرة سابقة لشنغن أو أمريكا أو بريطانيا أو كندا أو أستراليا أو نيوزيلندا',
      required: false,
    },
    {
      id: 'civil-id-copy',
      label: 'Civil ID copy',
      labelAr: 'نسخة البطاقة المدنية',
      required: true,
    },
    {
      id: 'travel-ticket',
      label: 'Travel ticket / flight reservation',
      labelAr: 'تذكرة السفر / حجز الرحلة',
      required: true,
    },
    {
      id: 'accommodation-confirmation',
      label: 'Accommodation confirmation',
      labelAr: 'تأكيد السكن',
      required: true,
    },
    {
      id: 'medical-insurance',
      label: 'Medical insurance',
      labelAr: 'التأمين الطبي',
      required: true,
    },
    {
      id: 'travel-insurance',
      label: 'Health and travel insurance',
      labelAr: 'التأمين الصحي وتأمين السفر',
      required: true,
    },
    {
      id: 'acceptance-letter',
      label: 'University acceptance letter',
      labelAr: 'خطاب قبول الجامعة',
      required: true,
    },
    {
      id: 'visa-support-letter',
      label: 'University visa support letter',
      labelAr: 'خطاب دعم التأشيرة من الجامعة',
      required: true,
    },
    {
      id: 'financial-guarantee-letter',
      label: 'Financial guarantee letter',
      labelAr: 'خطاب الضمان المالي',
      required: false,
      visibleWhen: { fieldId: 'funding-source', equals: 'Government / Scholarship' },
    },
    {
      id: 'scholarship-confirmation',
      label: 'Confirmation of scholarship',
      labelAr: 'تأكيد المنحة الدراسية',
      required: false,
      visibleWhen: { fieldId: 'funding-source', equals: 'Government / Scholarship' },
    },
    {
      id: 'sponsor-salary-docs',
      label: 'Sponsor salary documents',
      labelAr: 'مستندات راتب الكفيل',
      required: false,
      visibleWhen: {
        fieldId: 'funding-source',
        equals: 'Sponsored by Parent / Family Member / Other Sponsor',
      },
    },
    {
      id: 'sponsor-bank-statement',
      label: 'Sponsor bank statement',
      labelAr: 'كشف حساب الكفيل البنكي',
      required: false,
      visibleWhen: {
        fieldId: 'funding-source',
        equals: 'Sponsored by Parent / Family Member / Other Sponsor',
      },
    },
    {
      id: 'sponsorship-letter',
      label: 'Sponsorship letter',
      labelAr: 'خطاب الكفالة',
      required: false,
      visibleWhen: {
        fieldId: 'funding-source',
        equals: 'Sponsored by Parent / Family Member / Other Sponsor',
      },
    },
    {
      id: 'student-bank-statement',
      label: 'Student bank statement / proof of funds',
      labelAr: 'كشف حساب الطالب البنكي / إثبات الملاءة المالية',
      required: false,
      visibleWhen: { fieldId: 'funding-source', equals: 'Self-Funded' },
    },
    {
      id: 'travel-consent-letter',
      label: 'Travel consent letter',
      labelAr: 'خطاب الموافقة على السفر',
      required: false,
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
    },
    {
      id: 'birth-certificate',
      label: 'Birth certificate in English',
      labelAr: 'شهادة الميلاد باللغة الإنجليزية',
      required: false,
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
    },
    {
      id: 'father-passport-copy',
      label: "Father's passport copy",
      labelAr: 'نسخة جواز سفر الأب',
      required: false,
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
    },
    {
      id: 'father-civil-id-copy',
      label: "Father's civil ID copy",
      labelAr: 'نسخة البطاقة المدنية للأب',
      required: false,
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
    },
    {
      id: 'mother-passport-copy',
      label: "Mother's passport copy",
      labelAr: 'نسخة جواز سفر الأم',
      required: false,
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
    },
    {
      id: 'mother-civil-id-copy',
      label: "Mother's civil ID copy",
      labelAr: 'نسخة البطاقة المدنية للأم',
      required: false,
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
    },
  ],
  fields: [
    field({
      id: 'dob',
      type: 'date',
      label: 'Date of birth',
      labelAr: 'تاريخ الميلاد',
      required: true,
    }),
    field({
      id: 'nationality',
      type: 'text',
      label: 'Nationality',
      labelAr: 'الجنسية',
      required: true,
    }),
    field({
      id: 'civil-id',
      type: 'text',
      label: 'Civil ID number',
      labelAr: 'رقم البطاقة المدنية',
      required: true,
    }),
    field({
      id: 'under-18',
      type: 'radio',
      label: 'Are you under 18 years of age?',
      labelAr: 'هل عمرك أقل من 18 سنة؟',
      required: true,
      defaultValue: 'No',
    }),
    field({
      id: 'home-address',
      type: 'textarea',
      label: 'Home address',
      labelAr: 'عنوان السكن',
      required: true,
    }),
    field({
      id: 'email',
      type: 'email',
      label: 'Email address',
      labelAr: 'البريد الإلكتروني',
      required: true,
    }),
    field({
      id: 'funding-source',
      type: 'select',
      label: 'How will your studies be funded?',
      labelAr: 'كيف سيتم تمويل دراستك؟',
      required: true,
      options: [
        'Select...',
        'Government / Scholarship',
        'Sponsored by Parent / Family Member / Other Sponsor',
        'Self-Funded',
      ],
      optionsAr: [
        'اختر...',
        'حكومي / منحة دراسية',
        'برعاية والد / فرد من العائلة / كفيل آخر',
        'تمويل ذاتي',
      ],
    }),
    conditionalSection({
      id: 'sponsor-details',
      label: 'Sponsor details',
      labelAr: 'تفاصيل الكفيل',
      visibleWhen: {
        fieldId: 'funding-source',
        equals: 'Sponsored by Parent / Family Member / Other Sponsor',
      },
      fields: [
        field({
          id: 'sponsor-full-name',
          type: 'text',
          label: 'Sponsor full name',
          labelAr: 'الاسم الكامل للكفيل',
          required: false,
        }),
        field({
          id: 'sponsor-relationship',
          type: 'select',
          label: 'Relationship to student',
          labelAr: 'صلة القرابة بالطالب',
          required: false,
          options: ['Select...', 'Parent', 'Sibling', 'Relative', 'Other'],
          optionsAr: ['اختر...', 'والد/والدة', 'أخ/أخت', 'قريب', 'آخر'],
        }),
      ],
    }),
    conditionalSection({
      id: 'under18-parents',
      label: "Parents' contact details",
      labelAr: 'بيانات التواصل مع الوالدين',
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
      fields: [
        field({
          id: 'father-full-name',
          type: 'text',
          label: "Father's full name",
          labelAr: 'الاسم الكامل للأب',
          required: false,
        }),
        field({
          id: 'father-email',
          type: 'email',
          label: "Father's email address",
          labelAr: 'البريد الإلكتروني للأب',
          required: false,
        }),
        field({
          id: 'father-phone',
          type: 'tel',
          label: "Father's contact number",
          labelAr: 'رقم هاتف الأب',
          required: false,
        }),
        field({
          id: 'mother-full-name',
          type: 'text',
          label: "Mother's full name",
          labelAr: 'الاسم الكامل للأم',
          required: false,
        }),
        field({
          id: 'mother-email',
          type: 'email',
          label: "Mother's email address",
          labelAr: 'البريد الإلكتروني للأم',
          required: false,
        }),
        field({
          id: 'mother-phone',
          type: 'tel',
          label: "Mother's contact number",
          labelAr: 'رقم هاتف الأم',
          required: false,
        }),
      ],
    }),
    field({
      id: 'other-contact-toggle',
      type: 'radio',
      label: 'Do you want to provide other contact details?',
      labelAr: 'هل ترغب بإضافة بيانات تواصل أخرى؟',
      required: true,
      defaultValue: 'No',
    }),
    conditionalSection({
      id: 'other-contact',
      label: 'Additional contact details — other than parents',
      labelAr: 'بيانات تواصل إضافية (غير الوالدين)',
      visibleWhen: { fieldId: 'other-contact-toggle', equals: 'Yes' },
      fields: [
        field({
          id: 'other-contact-name',
          type: 'text',
          label: 'Full name',
          labelAr: 'الاسم الكامل',
          required: false,
        }),
        field({
          id: 'other-contact-relationship',
          type: 'select',
          label: 'Relationship to student',
          labelAr: 'صلة القرابة بالطالب',
          required: false,
          options: ['Select...', 'Relative', 'Guardian', 'Family Friend', 'Other'],
          optionsAr: ['اختر...', 'قريب', 'ولي أمر', 'صديق العائلة', 'آخر'],
        }),
        field({
          id: 'other-contact-phone',
          type: 'tel',
          label: 'Contact number',
          labelAr: 'رقم الهاتف',
          required: false,
        }),
        field({
          id: 'other-contact-email',
          type: 'email',
          label: 'Email address',
          labelAr: 'البريد الإلكتروني',
          required: false,
        }),
        field({
          id: 'other-contact-address',
          type: 'textarea',
          label: 'Home address',
          labelAr: 'عنوان السكن',
          required: false,
        }),
      ],
    }),
  ],
  serviceChargeKd: 35,
}
