import {
  field,
  repeatGroup,
  conditionalSection,
  type ServiceFormSchema,
} from '../applicationFieldSchema'

export const newZealandStudentSchema: ServiceFormSchema = {
  serviceCode: 'new-zealand-student',
  documents: [
    { id: 'passport-copy', label: 'Passport copy', labelAr: 'نسخة جواز السفر', required: true },
    {
      id: 'civil-id-copy',
      label: 'Civil ID copy',
      labelAr: 'نسخة البطاقة المدنية',
      required: true,
    },
    {
      id: 'police-clearance-certificate',
      label: 'Police clearance certificate',
      labelAr: 'شهادة حسن السيرة والسلوك',
      required: true,
    },
    { id: 'offer-letter', label: 'Offer letter', labelAr: 'خطاب القبول', required: true },
    {
      id: 'progression-year-offer',
      label: 'Progression year offer',
      labelAr: 'خطاب عرض السنة الدراسية التالية',
      required: true,
    },
    { id: 'digital-photo', label: 'Digital photo', labelAr: 'صورة شخصية رقمية', required: true },
    { id: 'ielts-certificate', label: 'IELTS', labelAr: 'آيلتس', required: true },
    {
      id: 'certificate-12th',
      label: '12th Certificate',
      labelAr: 'شهادة الصف الثاني عشر',
      required: true,
    },
    {
      id: 'personal-statement',
      label: 'Personal statement',
      labelAr: 'البيان الشخصي',
      required: true,
    },
    {
      id: 'father-passport-copy',
      label: "Father's passport copy",
      labelAr: 'نسخة جواز سفر الأب',
      required: false,
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
    },
    {
      id: 'mother-passport-copy',
      label: "Mother's passport copy",
      labelAr: 'نسخة جواز سفر الأم',
      required: false,
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
    },
    {
      id: 'bank-statement-nz',
      label: 'Bank statement',
      labelAr: 'كشف حساب بنكي',
      required: true,
      visibleWhen: { fieldId: 'proof-of-finance', equals: 'Self-Funded' },
    },
    {
      id: 'tuition-fee-receipt',
      label: 'Tuition fee receipt',
      labelAr: 'إيصال الرسوم الدراسية',
      required: true,
      visibleWhen: { fieldId: 'proof-of-finance', equals: 'Self-Funded' },
    },
  ],
  fields: [
    field({
      id: 'previous-nz-visa',
      type: 'radio',
      label: 'Have you previously applied for a New Zealand visa?',
      labelAr: 'هل تقدمت لتأشيرة نيوزيلندا من قبل؟',
      required: true,
      defaultValue: 'No',
    }),
    field({
      id: 'email',
      type: 'email',
      label: 'Current email address',
      labelAr: 'البريد الإلكتروني الحالي',
      required: true,
    }),
    field({
      id: 'address',
      type: 'textarea',
      label: 'Current physical address',
      labelAr: 'العنوان الحالي',
      required: true,
    }),
    field({
      id: 'travel-date-nz',
      type: 'date',
      label: 'What date do you intend to arrive in New Zealand?',
      labelAr: 'ما هو التاريخ المتوقع لوصولك إلى نيوزيلندا؟',
      required: true,
    }),
    field({
      id: 'convicted',
      type: 'radio',
      label: 'Have you ever been convicted?',
      labelAr: 'هل سبق وصدر بحقك حكم قضائي؟',
      required: true,
      defaultValue: 'No',
    }),
    field({
      id: 'visa-refused-any-country',
      type: 'radio',
      label: 'Have you ever been refused a visa for any country?',
      labelAr: 'هل سبق ورُفض طلب تأشيرة لك من أي دولة؟',
      required: true,
      defaultValue: 'No',
    }),
    field({
      id: 'under-18',
      type: 'radio',
      label: 'Are you under 18 years of age?',
      labelAr: 'هل عمرك أقل من 18 سنة؟',
      required: true,
      defaultValue: 'No',
    }),
    conditionalSection({
      id: 'under18-parents',
      label: "Parents' details",
      labelAr: 'بيانات الوالدين',
      visibleWhen: { fieldId: 'under-18', equals: 'Yes' },
      fields: [
        field({
          id: 'parent1-profession',
          type: 'text',
          label: 'Parent 1 — Profession',
          labelAr: 'مهنة الوالد 1',
          required: false,
        }),
        field({
          id: 'parent2-profession',
          type: 'text',
          label: 'Parent 2 — Profession',
          labelAr: 'مهنة الوالد 2',
          required: false,
        }),
      ],
    }),
    field({
      id: 'marital-status',
      type: 'select',
      label: 'Marital status',
      labelAr: 'الحالة الاجتماعية',
      required: true,
      options: ['Single', 'Married', 'Divorced', 'Widowed'],
      optionsAr: ['أعزب', 'متزوج', 'مطلق', 'أرمل'],
      defaultValue: 'Single',
    }),
    field({
      id: 'proof-of-finance',
      type: 'select',
      label: 'Proof of finance',
      labelAr: 'إثبات الملاءة المالية',
      required: true,
      options: ['Select...', 'Self-Funded', 'Sponsored'],
      optionsAr: ['اختر...', 'تمويل ذاتي', 'كفيل'],
    }),
    repeatGroup({
      id: 'international-flights',
      label: 'Last 5 international flights other than New Zealand (if applicable)',
      labelAr: 'آخر 5 رحلات دولية بخلاف نيوزيلندا (إن وجدت)',
      count: 5,
      required: false,
      columns: [
        { id: 'country', type: 'text', placeholder: 'Country', placeholderAr: 'الدولة' },
        { id: 'length', type: 'text', placeholder: 'Duration', placeholderAr: 'المدة' },
      ],
    }),
  ],
  serviceChargeKd: 80,
}
