import { field, repeatGroup, type ServiceFormSchema } from '../applicationFieldSchema'

export const ukStudentSchema: ServiceFormSchema = {
  serviceCode: 'uk-student',
  documents: [
    { id: 'passport-copy', label: 'Passport copy', labelAr: 'نسخة جواز السفر', required: true },
    {
      id: 'cas-visa-copy',
      label: 'CAS / Visa copy',
      labelAr: 'نسخة CAS / التأشيرة',
      required: true,
    },
    {
      id: 'father-passport-upload',
      label: "Father's passport",
      labelAr: 'جواز سفر الأب',
      required: false,
      hint: 'Attach a copy or fill the details below',
      hintAr: 'أرفق نسخة أو املأ التفاصيل أدناه',
    },
    {
      id: 'mother-passport-upload',
      label: "Mother's passport",
      labelAr: 'جواز سفر الأم',
      required: false,
      hint: 'Attach a copy or fill the details below',
      hintAr: 'أرفق نسخة أو املأ التفاصيل أدناه',
    },
    {
      id: 'financial-guarantee-letter',
      label: 'Financial guarantee letter',
      labelAr: 'خطاب الضمان المالي',
      required: true,
      visibleWhen: { fieldId: 'proof-of-finance', equals: 'Sponsor' },
    },
    {
      id: 'to-whom-it-may-concern-letter',
      label: 'To whom it may concern letter',
      labelAr: 'خطاب "إلى من يهمه الأمر"',
      required: true,
      visibleWhen: { fieldId: 'proof-of-finance', equals: 'Sponsor' },
    },
    {
      id: 'offer-approval-letter',
      label: 'Offer approval letter',
      labelAr: 'خطاب قبول العرض',
      required: true,
      visibleWhen: { fieldId: 'proof-of-finance', equals: 'Sponsor' },
    },
    {
      id: 'bank-statement',
      label: 'Bank statement',
      labelAr: 'كشف حساب بنكي',
      required: true,
      visibleWhen: { fieldId: 'proof-of-finance', equals: 'Self-Funded' },
    },
  ],
  fields: [
    field({
      id: 'renewed-passport',
      type: 'radio',
      label: 'Renewed passport recently?',
      labelAr: 'هل جددت جواز سفرك مؤخرًا؟',
      required: false,
      defaultValue: 'No',
    }),
    field({
      id: 'email',
      type: 'email',
      label: 'Email',
      labelAr: 'البريد الإلكتروني',
      required: true,
    }),
    field({ id: 'address', type: 'text', label: 'Address', labelAr: 'العنوان', required: true }),
    field({
      id: 'marital-status',
      type: 'select',
      label: 'Marital status',
      labelAr: 'الحالة الاجتماعية',
      required: true,
      options: ['Single', 'Married', 'Divorced', 'Widowed'],
      optionsAr: ['أعزب', 'متزوج', 'مطلق', 'أرمل'],
      defaultValue: 'Single',
    }),
    field({
      id: 'has-kids',
      type: 'radio',
      label: 'Do you have kids?',
      labelAr: 'هل لديك أطفال؟',
      required: false,
      defaultValue: 'No',
    }),
    field({
      id: 'proof-of-finance',
      type: 'select',
      label: 'Proof of finance',
      labelAr: 'إثبات الملاءة المالية',
      required: false,
      options: ['Select...', 'Self-Funded', 'Sponsor'],
      optionsAr: ['اختر...', 'تمويل ذاتي', 'كفيل'],
    }),
    field({
      id: 'father-fullname',
      type: 'text',
      label: "Father's full name",
      labelAr: 'الاسم الكامل للأب',
      required: false,
      hint: 'As shown in passport',
      hintAr: 'كما هو مذكور في جواز السفر',
    }),
    field({
      id: 'father-dob',
      type: 'date',
      label: "Father's date of birth",
      labelAr: 'تاريخ ميلاد الأب',
      required: false,
    }),
    field({
      id: 'mother-fullname',
      type: 'text',
      label: "Mother's full name",
      labelAr: 'الاسم الكامل للأم',
      required: false,
      hint: 'As shown in passport',
      hintAr: 'كما هو مذكور في جواز السفر',
    }),
    field({
      id: 'mother-dob',
      type: 'date',
      label: "Mother's date of birth",
      labelAr: 'تاريخ ميلاد الأم',
      required: false,
    }),
    field({
      id: 'mother-nationality',
      type: 'text',
      label: "Mother's nationality",
      labelAr: 'جنسية الأم',
      required: false,
    }),
    field({
      id: 'uk-visa-before',
      type: 'radio',
      label: 'Got a UK visa before?',
      labelAr: 'هل حصلت على تأشيرة بريطانية من قبل؟',
      required: true,
      defaultValue: 'No',
    }),
    field({
      id: 'visa-rejection-before',
      type: 'radio',
      label: 'Ever had a visa rejection before?',
      labelAr: 'هل سبق ورُفض طلب تأشيرة لك؟',
      required: true,
      defaultValue: 'No',
    }),
    field({
      id: 'uk-medical-before',
      type: 'radio',
      label: 'Ever treated in the UK before?',
      labelAr: 'هل تلقيت علاجًا طبيًا في بريطانيا من قبل؟',
      required: true,
      defaultValue: 'No',
    }),
    repeatGroup({
      id: 'uk-visits',
      label: 'Last 3 visits to the UK',
      labelAr: 'آخر 3 زيارات لبريطانيا',
      count: 3,
      columns: [
        { id: 'date', type: 'date', placeholder: 'Date', placeholderAr: 'التاريخ' },
        { id: 'length', type: 'text', placeholder: 'Length of stay', placeholderAr: 'مدة الإقامة' },
      ],
    }),
    repeatGroup({
      id: 'international-flights',
      label: 'Last 5 international flights (excluding UK)',
      labelAr: 'آخر 5 رحلات دولية (بخلاف بريطانيا)',
      count: 5,
      columns: [
        { id: 'date', type: 'date', placeholder: 'Date', placeholderAr: 'التاريخ' },
        { id: 'length', type: 'text', placeholder: 'Length', placeholderAr: 'المدة' },
        { id: 'country', type: 'text', placeholder: 'Country', placeholderAr: 'الدولة' },
      ],
    }),
    field({
      id: 'travel-date-uk',
      type: 'date',
      label: 'Estimated travel date to the UK',
      labelAr: 'التاريخ المتوقع للسفر إلى بريطانيا',
      required: false,
    }),
  ],
  serviceChargeKd: 35,
}
