import { field, repeatGroup, type ServiceFormSchema } from '../applicationFieldSchema'

export const usF1Schema: ServiceFormSchema = {
  serviceCode: 'us-f1',
  documents: [
    { id: 'passport-copy', label: 'Passport copy', labelAr: 'نسخة جواز السفر', required: true },
    { id: 'i20-form', label: 'I-20 form', labelAr: 'نموذج I-20', required: true },
    {
      id: 'passport-photo',
      label: 'Passport-sized photo',
      labelAr: 'صورة شخصية بحجم جواز السفر',
      required: true,
      hint: 'White background',
      hintAr: 'خلفية بيضاء',
    },
    {
      id: 'father-passport-upload',
      label: "Father's passport",
      labelAr: 'جواز سفر الأب',
      required: true,
    },
    {
      id: 'mother-passport-upload',
      label: "Mother's passport",
      labelAr: 'جواز سفر الأم',
      required: true,
    },
    {
      id: 'bank-statement',
      label: 'Bank statement',
      labelAr: 'كشف حساب بنكي',
      required: true,
      visibleWhen: { fieldId: 'proof-of-finance', equals: 'Self-Funded' },
    },
    {
      id: 'scholarship-confirmation',
      label: 'Confirmation of scholarship',
      labelAr: 'تأكيد المنحة الدراسية',
      required: true,
      visibleWhen: { fieldId: 'proof-of-finance', equals: 'Sponsor' },
    },
  ],
  fields: [
    field({
      id: 'email',
      type: 'email',
      label: 'Email',
      labelAr: 'البريد الإلكتروني',
      required: true,
    }),
    field({
      id: 'phone-primary',
      type: 'tel',
      label: 'Primary phone',
      labelAr: 'رقم الهاتف الأساسي',
      required: true,
    }),
    field({
      id: 'phone-secondary',
      type: 'tel',
      label: 'Secondary phone',
      labelAr: 'رقم الهاتف الثانوي',
      required: true,
    }),
    field({
      id: 'residential-address',
      type: 'text',
      label: 'Residential address',
      labelAr: 'عنوان السكن',
      required: true,
    }),
    field({
      id: 'social-media',
      type: 'textarea',
      label: 'Social media usernames',
      labelAr: 'أسماء المستخدمين لحسابات التواصل الاجتماعي',
      required: true,
      hint: 'All platforms, past 5 years',
      hintAr: 'جميع المنصات، آخر 5 سنوات',
    }),
    field({
      id: 'countries-traveled',
      type: 'textarea',
      label: 'Countries traveled to',
      labelAr: 'الدول التي سافرت إليها',
      required: true,
      hint: 'Past 5 years',
      hintAr: 'آخر 5 سنوات',
    }),
    field({
      id: 'marital-status',
      type: 'select',
      label: 'Marital status',
      labelAr: 'الحالة الاجتماعية',
      required: true,
      options: ['Single', 'Married', 'Divorced', 'Widowed'],
      optionsAr: ['أعزب', 'متزوج', 'مطلق', 'أرمل'],
      defaultValue: 'Single',
    }),
    field({
      id: 'proof-of-finance',
      type: 'select',
      label: 'Proof of finance',
      labelAr: 'إثبات الملاءة المالية',
      required: true,
      options: ['Self-Funded', 'Sponsor'],
      optionsAr: ['تمويل ذاتي', 'كفيل'],
      defaultValue: 'Self-Funded',
    }),
    field({
      id: 'father-fullname',
      type: 'text',
      label: "Father's full name",
      labelAr: 'الاسم الكامل للأب',
      required: true,
      hint: 'As shown in passport',
      hintAr: 'كما هو مذكور في جواز السفر',
    }),
    field({
      id: 'father-dob',
      type: 'date',
      label: "Father's date of birth",
      labelAr: 'تاريخ ميلاد الأب',
      required: true,
    }),
    field({
      id: 'mother-fullname',
      type: 'text',
      label: "Mother's full name",
      labelAr: 'الاسم الكامل للأم',
      required: true,
      hint: 'As shown in passport',
      hintAr: 'كما هو مذكور في جواز السفر',
    }),
    field({
      id: 'mother-dob',
      type: 'date',
      label: "Mother's date of birth",
      labelAr: 'تاريخ ميلاد الأم',
      required: true,
    }),
    field({
      id: 'been-to-us',
      type: 'radio',
      label: 'Ever been to the United States?',
      labelAr: 'هل سبق وزرت الولايات المتحدة؟',
      required: true,
      defaultValue: 'No',
    }),
    field({
      id: 'lost-passport',
      type: 'radio',
      label: 'Ever lost your passport?',
      labelAr: 'هل سبق وفقدت جواز سفرك؟',
      required: true,
      defaultValue: 'No',
    }),
    field({
      id: 'applied-visa-before',
      type: 'radio',
      label: 'Applied for US visa before?',
      labelAr: 'هل تقدمت لتأشيرة أمريكية من قبل؟',
      required: true,
      defaultValue: 'No',
    }),
    field({
      id: 'rejected-visa-before',
      type: 'radio',
      label: 'Ever rejected for a visa?',
      labelAr: 'هل سبق ورُفض طلب تأشيرة لك؟',
      required: true,
      defaultValue: 'No',
    }),
    repeatGroup({
      id: 'references',
      label: 'Two unrelated references',
      labelAr: 'مرجعان (شخصان) غير أقارب',
      count: 2,
      required: true,
      columns: [
        { id: 'name', type: 'text', placeholder: 'Full name', placeholderAr: 'الاسم الكامل' },
        { id: 'phone', type: 'text', placeholder: 'Phone', placeholderAr: 'الهاتف' },
        {
          id: 'address',
          type: 'text',
          placeholder: 'Address in Kuwait',
          placeholderAr: 'العنوان في الكويت',
        },
      ],
    }),
    field({
      id: 'relatives-usa',
      type: 'radio',
      label: 'Relatives in the USA?',
      labelAr: 'هل لديك أقارب في الولايات المتحدة؟',
      required: true,
      defaultValue: 'No',
    }),
    field({
      id: 'ever-employed',
      type: 'radio',
      label: 'Ever employed?',
      labelAr: 'هل سبق وعملت؟',
      required: true,
      defaultValue: 'No',
    }),
    field({
      id: 'after-graduation',
      type: 'text',
      label: 'What did you do after graduation?',
      labelAr: 'ماذا فعلت بعد التخرج؟',
      required: true,
    }),
  ],
  serviceChargeKd: 35,
}
